name: udvanced_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  retrofit: ^3.0.1+1
  analyzer: ^3.4.1
  dio: ^4.0.6
  json_serializable: ^6.1.6
  dartz: ^0.10.1


  cupertino_icons: ^1.0.4
  internet_connection_checker: ^0.0.1+3
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.13
  freezed: ^1.1.1
  get_it: ^7.2.0
  lottie: ^1.3.0
  country_code_picker: ^2.0.2
  image_picker: ^0.8.5
  rxdart: ^0.27.3
  carousel_slider: ^4.1.1
  easy_localization: ^3.0.1
  flutter_phoenix: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.10


  flutter_lints: ^1.0.4


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/splash_logo.png
     - assets/images/onboarding_logo1.svg
     - assets/images/onboarding_logo2.svg
     - assets/images/onboarding_logo3.svg
     - assets/images/onboarding_logo4.svg
     - assets/images/onboarding_logo4.svg
     - assets/images/arrow_left_ic.svg
     - assets/images/arrow_right_ic.svg
     - assets/images/hollow_circle_ic.svg
     - assets/images/solid_circle_ic.svg
     - assets/images/photo_camera.svg
     - assets/json/loading.json
     - assets/json/error.json
     - assets/json/empty.json
     - assets/json/success.json
     - assets/translations/ar-SA.json
     - assets/translations/en-US.json
     - assets/images/invite_friends_ic.svg
     - assets/images/logout_ic.svg
     - assets/images/settings_ic.svg
     - assets/images/setting_arrow_ic.svg
     - assets/images/contact_us_ic.svg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

